### PR TITLE
create dynamic client for packagemanifest.

### PR DESCRIPTION
**Pull request by morvencao**
this PR tries to fix packagemenifest access issue with controller-runtime client.

use another dynamic client to get packagemenifest instead of controller-runtime client.

Signed-off-by: morvencao <lcao@redhat.com>

### CODE REVIEW

**Comment by clyang82** [comment]
Great work 💯 
You need to force push to retrigger the prow checks.

**Comment by clyang82** [comment]
/hold

Please run `make fmt` to format the code to fix the code smells.

**Comment by morvencao** [comment]
fixed code small, PTAL @clyang82

**Pull request merged**
