### PR TITLE
Update components' name

### PR DESCRIPTION
**Pull request by clyang82**
ref: https://github.com/stolostron/backlog/issues/25025
Signed-off-by: clyang82 <chuyang@redhat.com>

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
/lgtm

**Review by morvencao — COMMENTED** [review]
/lgtm

**Review by morvencao — COMMENTED** [review]
/lgtm

**Review by morvencao — COMMENTED** [review]
/lgtm

**Comment by clyang82** [comment]
depends on https://github.com/stolostron/multicluster-globalhub/pull/132

**Review by morvencao — COMMENTED** [review]
/lgtm

**Pull request merged**
