### PR TITLE
Share kafka and databse setup between operater samples and e2e setup

### PR DESCRIPTION
**Pull request by yanmxa**
Signed-off-by: myan <myan@redhat.com>
Reference: https://github.com/stolostron/backlog/issues/24610

### CODE REVIEW

**Comment by clyang82** [comment]
Don't we need to remove the existing files in `https://github.com/stolostron/multicluster-globalhub/tree/main/test/setup/postgres`?

**Comment by yanmxa** [comment]
> Don't we need to remove the existing files in `https://github.com/stolostron/multicluster-globalhub/tree/main/test/setup/postgres`?

We will remove the `test/setup/postgres` and `test/setup/kafka` files at another PR which will switch the setup process with **operator**.

**Pull request merged**
