### PR TITLE
Use operator in e2e tests

### PR DESCRIPTION
**Pull request by clyang82**
Signed-off-by: clyang82 <chuyang@redhat.com>

### CODE REVIEW

**Comment by yanmxa** [comment]
It seems you need to add the `MULTICLUSTER_GLOBALHUB_OPERATOR_IMAGE_REF` environment in the `cicd-scripts/run-prow-e2e-test.sh`, so that the [hoh_setup.sh](https://github.com/stolostron/multicluster-globalhub/blob/c21a0118cee3f842ce9bcb88d71b4a7399d6d896/test/setup/hoh/hoh_setup.sh#L25) can use the operator to setup the HoH environment.

**Review by morvencao — COMMENTED** [review]
/lgtm

**Comment by yanmxa** [comment]
Fixed: https://github.com/stolostron/backlog/issues/24610

**Pull request merged**
